### ISSUE TITLE
Only works for a second then stops

### ISSUE THREAD

**Issue by sm1th** [knobtviker/bme280#4]
Using version 1.1.4, and Android Things 1.0

I register just the temperature sensor in onCreate of my main activity. It seems to read a few times when I first launch the app, but then stops. Any ideas what could be causing this?

**Comment by knobtviker** [comment]
it's a bug, under investigation at the moment. I'm seeing the same as of DP8.

**Comment by sm1th** [comment]
Any update on this?

**Comment by knobtviker** [comment]
Fixed in 1.1.5 please update your dependency.

**Comment by sm1th** [comment]
Thanks, I'll test hopefully this weekend.

**Comment by sm1th** [comment]
Working for me! Well, this particular issue is fixed but I'm seeing other problems. Will open another issue.

Thank you!
