### ISSUE TITLE
Will not recover if BME280 unplugged & plugged in again.

### ISSUE THREAD

**Issue by josmithua** [knobtviker/bme280#5]
Driver version: 1.1.5
Android Things 1.0

Just registered to the temperature sensor.

1. If I unplug the data or clock from the BME280 and then plug it in again, it will start to send back garbage (usually numbers below -120ºC)
2. If I unplug power from the BME280 and then plug it in again, it will not connect/send back anything, until I unplug either the data or clock and plug in again. Then it will send back garbage (as in number 1 above).

I admit the physical disconnection of the sensor is not a common occurrence, but it would be nice if it could recover gracefully without having to restart the device.

**Comment by knobtviker** [comment]
I have seen similar behavior when for some reason I2C bus would drop dead.
You provided a test use case now. :)
Yes, graceful recovery would be very desirable.
I'll see what I can do and will get back to you.

**Comment by knobtviker** [comment]
I couldn't find a nice and elegant way to handle this behaviour.
I asked, and was told, by Googlers, that peripheral devices as such are not meant to be hotplugged like that. No underlying APIs on Things can handle such incidents.
I agree with you, there should be a fallback mechanism, but there is nothing I can do on a driver level at the moment, sorry.
[Discussion link here](https://plus.google.com/104823142370815890510/posts/PobsrfbKKSG)

**Comment by sm1th** [comment]
No problem, thanks for looking into this.
